on: 
 push:
  branches:
    - master
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    name: "JolieDoc Build"
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: fmontesi
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./Dockerfile
          push: true
          tags: jolielang/jolie-docs:latest
     
