on: 
 push:
  branches:
    - v1.9.x
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    name: "Trigger"
    uses: actions/checkout@v2
      with:
        token: ${{secrets.PAT}}
    - run: |
        git push
