on: 
 push:
  branches:
    - v1.9.x
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    name: "Trigger"
    steps:
     - uses: actions/hello-world-docker-action@master
       with:
         who-to-greet: 'Version 1.9.0'
