on: 
 push:
  branches:
    - master
    - v1.9.x
    - v1.10.x 
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    name: "JolieDoc Build"
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: fmontesi
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }} 
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          push: true
          tags: jolielang/docs:latest
