on: 
 push:
  branches:
    - v1.9.x
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    name: "Trigger"
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        token: ${{secrets.PAT}}
    - run:  git branch | git commit --allow-empty -m "Triggered by v1.9.x" | git push
