on: 
 push:
  branches:
    - master
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    name: "JolieDoc Build"
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: balintpixis
          password: 4e0a7bad-b33d-41b3-b56a-2e9762b027d4  
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./Dockerfile
          push: true
          tags: jolielang/docs:latest
     
