on: 
 push:
  branches:
    - master
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    name: "JolieDoc Build"
    steps:
      - uses: actions/checkout@v1
      - name: ls
        run: ls  
      - name: Build Global Image
        run: docker build . --file ./docker/Dockerfile --tag jolie-docs --no-cache
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: fmontesi
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./all.Dockerfile
          push: true
          tags: jolielang/jolie-docs:latest
      
