on: 
  push:
    branches:
      - master
jobs:
  docker_build_and_deploy:
    runs-on: ubuntu-latest
    name: "Fafiec Frontend Dev Build and Deploy"
    strategy:
      matrix:
        node-version: [12.10.0]
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          npm i
          npm update
          npm build --prod
      - name: list
        run: ls    
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.GCR_MAIL_PROD}} 
          service_account_key: ${{ secrets.GCR_SECRET_PROD }}
          project_id: ${{ secrets.GCR_PROJECT_ID_PROD }}
      - name: gcloud
        run: gcloud auth configure-docker
      - name: Build the tagged Docker image
        run: docker build . --file DockerProd --tag eu.gcr.io/pxtestprj-260818/co.pixis.frontend:$GITHUB_SHA
      - name: publish  
        run: docker push eu.gcr.io/pxtestprj-260818/co.pixis.frontend:$GITHUB_SHA
      - name: Deploy
        run: gcloud compute instances update-container frontend	 --zone=europe-west1-b --container-image eu.gcr.io/pxtestprj-260818/co.pixis.frontend:$GITHUB_SHA